services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports: ["127.0.0.1:5678:5678"]
    volumes: ["n8n_data:/home/node/.n8n"]

  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on: [n8n]
    ports: ["80:80","443:443"]
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/www/dominionhealing:/var/www/dominionhealing:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  n8n_data:
  caddy_data:
  caddy_config:
